import { test } from "node:test";
import assert from "node:assert/strict";
import { compile } from "@stylec/compiler";
import { resolveStylecDefinition, type FileHost, type DefinitionInfo } from "../dist/index.js";

const cssFile = "/proj/Button.stylec.css";
const tsFile = "/proj/Button.stylec.ts";

function setup() {
  const source = ".button { color: red; }\n.icon { width: 16px; }\n";
  const { code } = compile(source, { filename: "Button.stylec.css" });
  const files: Record<string, string> = { [tsFile]: code, [cssFile]: source };
  const host: FileHost = (p) => files[p];
  return { source, code, host };
}

function defAt(fileName: string, offset: number, name: string, len = name.length): DefinitionInfo {
  return {
    fileName,
    textSpan: { start: offset, length: len },
    name,
    kind: "property",
    containerName: "",
    containerKind: "",
  };
}

test("redirects a classes property def to the CSS class name", () => {
  const { code, source, host } = setup();
  const off = code.indexOf('button: "s_button_');
  assert.ok(off >= 0);
  const out = resolveStylecDefinition(host, defAt(tsFile, off, "button"));
  assert.ok(out);
  assert.equal(out!.fileName, cssFile);
  assert.equal(out!.name, "button");
  assert.equal(out!.textSpan.start, source.indexOf("button"));
  assert.equal(out!.textSpan.length, "button".length);
});

test("redirects an override out entry too", () => {
  const { code, source, host } = setup();
  const off = code.indexOf('button: "s_button_" + h');
  assert.ok(off >= 0);
  const out = resolveStylecDefinition(host, defAt(tsFile, off, "button"));
  assert.ok(out);
  assert.equal(out!.fileName, cssFile);
  assert.equal(out!.textSpan.start, source.indexOf("button"));
});

test("resolves even when landing on the value (same line as the property)", () => {
  const { code, source, host } = setup();
  const propLine = code.indexOf('button: "s_button_');
  const valueOff = code.indexOf("s_button_", propLine);
  assert.ok(valueOff >= 0);
  const out = resolveStylecDefinition(host, defAt(tsFile, valueOff, "s_button_"));
  assert.ok(out);
  assert.equal(out!.fileName, cssFile);
  assert.equal(out!.textSpan.start, source.indexOf("button"));
});

test("leaves definitions in non-stylec files untouched", () => {
  const { host } = setup();
  assert.equal(resolveStylecDefinition(host, defAt("/proj/App.tsx", 0, "x", 1)), undefined);
});

test("returns undefined when landing outside any mapped region", () => {
  const { code, host } = setup();
  const off = code.indexOf("Generated by");
  assert.ok(off >= 0);
  assert.equal(resolveStylecDefinition(host, defAt(tsFile, off, "Generated", 8)), undefined);
});
