import {
  GenMapping,
  addMapping,
  setSourceContent,
  toEncodedMap,
  type EncodedSourceMap,
} from "@jridgewell/gen-mapping";
import { __hash } from "@stylec/runtime";

export const HASH_PLACEHOLDER = "\u0000";

export interface ClassInfo {
  name: string;
  line: number; // CSS source: 1-based line of the class-name token
  column: number; // CSS source: 0-based column of the class-name token
}

export interface CodegenInput {
  templateBody: string;
  classes: ClassInfo[];
  source: string;
  srcFile?: string | undefined;
}

export interface CodegenResult {
  code: string;
  hash: string;
  map: EncodedSourceMap | null;
}

interface Segment {
  genLine: number;
  genColumn: number;
  srcLine: number;
  srcColumn: number;
  name: string;
}

class Builder {
  private chunks: string[] = [];
  private line = 1;
  private col = 0;
  readonly segments: Segment[] = [];
  constructor(readonly srcFile: string) {}

  push(text: string, src?: { line: number; column: number; name: string }): this {
    if (src) {
      this.segments.push({
        genLine: this.line,
        genColumn: this.col,
        srcLine: src.line,
        srcColumn: src.column,
        name: src.name,
      });
    }
    this.chunks.push(text);
    for (let i = 0; i < text.length; i++) {
      if (text.charCodeAt(i) === 10) {
        this.line++;
        this.col = 0;
      } else {
        this.col++;
      }
    }
    return this;
  }

  toString(): string {
    return this.chunks.join("");
  }
}

function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function safeKey(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

export function generate(input: CodegenInput): CodegenResult {
  const hash = __hash(input.source);
  const parts = input.templateBody.split(HASH_PLACEHOLDER);
  const body = parts.map(escapeTemplateLiteral).join("${h}");

  const classInfo = input.classes;
  const srcFile = input.srcFile;
  const src = (c: ClassInfo) =>
    srcFile ? { line: c.line, column: c.column, name: c.name } : undefined;
  const b = new Builder(srcFile ?? "<unknown>");

  b.push("// Generated by @stylec/compiler. Do not edit.\n");
  b.push('import { __override, type CSSProperties } from "@stylec/runtime";\n\n');
  b.push(`export const cssHash = ${JSON.stringify(hash)};\n\n`);
  b.push("const _tmpl = (h: string) => `");
  b.push(body);
  b.push("`;\n\n");
  b.push("export const css = _tmpl(cssHash);\n\n");

  b.push("export const classes = {\n");
  for (const c of classInfo) {
    b.push("  ");
    b.push(safeKey(c.name), src(c));
    b.push(`: "${c.name}_${hash}",\n`);
  }
  b.push("} as const;\n");
  b.push("export type ClassName = keyof typeof classes;\n\n");

  b.push("const __names = [\n");
  for (const c of classInfo) {
    b.push("    ");
    b.push(JSON.stringify(c.name), src(c));
    b.push(",\n");
  }
  b.push("  ] as const;\n\n");
  b.push("export function override(patch: Partial<Record<ClassName, CSSProperties>>) {\n");
  b.push("  return __override(__names, _tmpl, cssHash, patch);\n");
  b.push("}\n");

  const code = b.toString();

  let map: EncodedSourceMap | null = null;
  if (srcFile && b.segments.length > 0) {
    const gm = new GenMapping({});
    setSourceContent(gm, srcFile, input.source);
    for (const seg of b.segments) {
      addMapping(gm, {
        generated: { line: seg.genLine, column: seg.genColumn },
        source: srcFile,
        original: { line: seg.srcLine, column: seg.srcColumn },
        name: seg.name,
      });
    }
    map = toEncodedMap(gm);
  }

  return { code, hash, map };
}
