import { test } from "node:test";
import assert from "node:assert/strict";
import { writeFileSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { compile } from "../dist/index.js";

const SRC = ".button { color: red; } .icon { width: 16px; }";

async function loadCompiled(source: string) {
  const { code } = compile(source);
  const file = join(import.meta.dirname, "__fixture__.ts");
  writeFileSync(file, code);
  try {
    return await import(file + "?t=" + Date.now());
  } finally {
    unlinkSync(file);
  }
}

test("generated module exports classes, css", async () => {
  const mod = await loadCompiled(SRC);
  assert.match(mod.classes.button, /^button_/);
  assert.match(mod.classes.icon, /^icon_/);
  assert.equal(typeof mod.css, "string");
  assert.ok(mod.css.includes("." + mod.classes.button));
});

test("override produces a scoped (new-hash) class", async () => {
  const mod = await loadCompiled(SRC);
  const v = mod.override({ button: { color: "green" } });
  assert.notEqual(v.classes.button, mod.classes.button);
  assert.match(v.classes.button, /^button_/);
});

test("override is deterministic for the same patch", async () => {
  const mod = await loadCompiled(SRC);
  const a = mod.override({ button: { color: "green" } });
  const b = mod.override({ button: { color: "green" } });
  assert.equal(a.classes.button, b.classes.button);
  assert.equal(a.css, b.css);
});

test("override merges: base declarations kept, override appended last", async () => {
  const mod = await loadCompiled(SRC);
  const v = mod.override({ button: { color: "green" } });
  // override rule (compact, generated by codegen)
  assert.ok(v.css.includes("." + v.classes.button + "{color:green;}"));
  // base declaration survived (original formatting preserved)
  assert.ok(v.css.includes("color: red"));
  // merge semantics: override comes AFTER base, so it wins the cascade
  const baseIdx = v.css.indexOf("color: red");
  const overIdx = v.css.indexOf("color:green");
  assert.ok(baseIdx < overIdx);
});

test("override only touches classes named in the patch", async () => {
  const mod = await loadCompiled(SRC);
  const v = mod.override({ icon: { width: "32px" } });
  assert.ok(v.css.includes("." + v.classes.icon + "{width:32px;}"));
  // no spurious green rule
  assert.ok(!v.css.includes("color:green"));
});
